<div style="font-size: 14pt;">Prof. Krzysztof Rybinski</div><br/><br/>
<div style="font-size: 22pt;"><b>Artificial Intelligence course</b></div><br/><br/>
<div style="font-size: 18pt;">LAB 1.</div><br/>
<div style="font-size: 18pt;">- Python refresher: numpy and pandas basic operations</div><br/>
<div style="font-size: 18pt;">- Creating environment</div><br/>


In [67]:
#!conda install -c anaconda numpy

In [68]:
#!conda install -c anaconda pandas

In [69]:
import numpy as np

In [70]:
import pandas as pd

# Scalar operations

In [71]:
X = np.asarray(5.0)

In [72]:
print(X)
print(X.shape)

5.0
()


# Vectors in numpy

In [73]:
X = np.array([5.0, 6.0, 7.0, 8.0])

In [74]:
print(X)

[5. 6. 7. 8.]


In [75]:
X

array([5., 6., 7., 8.])

In [76]:
X.shape

(4,)

In [77]:
X.T.shape

(4,)

In [78]:
X.T

array([5., 6., 7., 8.])

# Numpy matrix operations

In [79]:
X = np.array( [ [5.0, 6.0, 7.0],  [1.0, 2.0, 3.0] ] )

In [80]:
print(X)

[[5. 6. 7.]
 [1. 2. 3.]]


In [81]:
X.shape

(2, 3)

In [82]:
X.T

array([[5., 1.],
       [6., 2.],
       [7., 3.]])

In [83]:
X.T.shape

(3, 2)

---

# Vector-scalar operations in numpy

In [84]:
alpha = 0.5
y = np.array( [1.0, 2.0, 3.0 ])

In [85]:
alpha * y #elementwise

array([0.5, 1. , 1.5])

In [86]:
alpha + y #elementwise

array([1.5, 2.5, 3.5])

# Vector operations

In [87]:
x = np.asarray([1.0, 2.0, 3.0])
y = np.asarray([4.0, 5.0, 6.0])
z = np.asarray([7.0, 8.0])

In [88]:
x + y #elementwise

array([5., 7., 9.])

In [89]:
x * y #elementwise

array([ 4., 10., 18.])

In [90]:
x / x

array([1., 1., 1.])

In [91]:
np.dot(x,y) #sum over elementwise multiplications, vector times vector

32.0

In [92]:
x.dot(y)

32.0

In [93]:
x.dot(z)

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

In [ ]:
5*x+6*y

# Matrix - vector operations in numpy

In [ ]:
X = np.asarray([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0]])

In [ ]:
X

In [ ]:
X.shape

In [ ]:
y = np.asarray([1.0, 0.0, 1.0])
y

In [ ]:
y.shape

In [ ]:
X + y

In [ ]:
X-y

In [ ]:
X, y

In [ ]:
X*y #elementwise

In [ ]:
X.dot(y).shape[1]

In [ ]:
X.T.dot(y)

In [ ]:
X.dot(y.T)

In [ ]:
np.dot(X,y.T)

In [ ]:
y.dot(X)

In [ ]:
z = np.asarray( [1.0, 2.0 ])

In [ ]:
X

In [ ]:
z.dot(X)

In [ ]:
y.T.dot(X.T)

# Operations on matrices in numpy

In [ ]:
X = np.asarray([[1.0, 2.0, 3.0], [4.0, 6.0, 7.0]])
Y = np.asarray([[10.0, 20.0, 30.0, 40.0], [50.0, 60.0, 70.0, 80.0], [90.0, 100.0, 110.0, 120.0]])

In [ ]:
print(X)
print(X.shape)

In [ ]:
print(Y)
print(Y.shape)

In [ ]:
X*Y

In [ ]:
X.dot(Y)

In [ ]:
X+Y

In [ ]:
X.T.dot(X).shape

In [ ]:
Y=X.T.dot(X)
Y

In [ ]:
a = np.array([[1., 2.], [3., 4.]])
ainv = np.linalg.inv(a)

In [ ]:
a

In [ ]:
ainv

In [ ]:
np.dot(a,ainv)

# Basic operations in pandas

In [94]:
import pandas as pd

In [95]:
from sklearn import datasets

In [96]:
boston = datasets.load_boston()
boston_pd = pd.DataFrame( boston.data, columns=boston.feature_names )
boston_pd

/Users/nindaba/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California hou

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

<div style="font-size: 14pt;">check the meaning of column names at https://scikit-learn.org/stable/datasets/toy_dataset.html</div><br/><br/>

In [97]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [98]:
import os

In [99]:
os.getcwd()

'/Users/nindaba/Documents/vistula/semister-5/ai/general-info'

In [100]:
os.chdir("D:\\A1\\_Priv\\Vistula_AI_course_2022_Fall\\Results")
os.getcwd()

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\A1\\_Priv\\Vistula_AI_course_2022_Fall\\Results'

In [102]:
os.chdir("Lab_data")
os.getcwd()

FileNotFoundError: [Errno 2] No such file or directory: 'data'

In [103]:
X = boston_pd.to_numpy()

In [104]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [105]:
X.shape

(506, 13)

In [106]:
boston_pd.to_csv('boston_features.csv', index=False) #save data as csv file, drop index

In [107]:
boston_pd2 = pd.read_csv('boston_features.csv')

In [108]:
boston_pd2

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [109]:
boston_pd3 = boston_pd2[['CRIM', 'CHAS', 'NOX']]

In [110]:
boston_pd3.head()

CRIM  CHAS    NOX
0  0.00632   0.0  0.538
1  0.02731   0.0  0.469
2  0.02729   0.0  0.469
3  0.03237   0.0  0.458
4  0.06905   0.0  0.458

In [111]:
sel = boston_pd['RM'] > 7

In [117]:
boston_pd > 7

CRIM     ZN  INDUS   CHAS    NOX     RM   AGE    DIS    RAD   TAX  \
0    False   True  False  False  False  False  True  False  False  True   
1    False  False   True  False  False  False  True  False  False  True   
2    False  False   True  False  False   True  True  False  False  True   
3    False  False  False  False  False  False  True  False  False  True   
4    False  False  False  False  False   True  True  False  False  True   
..     ...    ...    ...    ...    ...    ...   ...    ...    ...   ...   
501  False  False   True  False  False  False  True  False  False  True   
502  False  False   True  False  False  False  True  False  False  True   
503  False  False   True  False  False  False  True  False  False  True   
504  False  False   True  False  False  False  True  False  False  True   
505  False  False   True  False  False  False  True  False  False  True   

     PTRATIO     B  LSTAT  
0       True  True  False  
1       True  True   True  
2       True  True  False  
3       True  True  False  
4       True  True  False  
..       ...   ...    ...  
501     True  True   True  
502     True  True   True  
503     True  True  False  
504     True  True  False  
505     True  True   True  

[506 rows x 13 columns]

In [112]:
sel

0      False
1      False
2       True
3      False
4       True
       ...  
501    False
502    False
503    False
504    False
505    False
Name: RM, Length: 506, dtype: bool

In [113]:
rmgt7 = boston_pd[sel] #select rows with RM > 7

In [114]:
rmgt7

CRIM    ZN  INDUS  CHAS     NOX     RM   AGE     DIS   RAD    TAX  \
2     0.02729   0.0   7.07   0.0  0.4690  7.185  61.1  4.9671   2.0  242.0   
4     0.06905   0.0   2.18   0.0  0.4580  7.147  54.2  6.0622   3.0  222.0   
40    0.03359  75.0   2.95   0.0  0.4280  7.024  15.8  5.4011   3.0  252.0   
55    0.01311  90.0   1.22   0.0  0.4030  7.249  21.9  8.6966   5.0  226.0   
64    0.01951  17.5   1.38   0.0  0.4161  7.104  59.5  9.2229   3.0  216.0   
..        ...   ...    ...   ...     ...    ...   ...     ...   ...    ...   
364   3.47428   0.0  18.10   1.0  0.7180  8.780  82.9  1.9047  24.0  666.0   
370   6.53876   0.0  18.10   1.0  0.6310  7.016  97.5  1.2024  24.0  666.0   
375  19.60910   0.0  18.10   0.0  0.6710  7.313  97.9  1.3163  24.0  666.0   
453   8.24809   0.0  18.10   0.0  0.7130  7.393  99.3  2.4527  24.0  666.0   
482   5.73116   0.0  18.10   0.0  0.5320  7.061  77.0  3.4106  24.0  666.0   

     PTRATIO       B  LSTAT  
2       17.8  392.83   4.03  
4       18.7  396.90   5.33  
40      18.3  395.62   1.98  
55      17.9  395.93   4.81  
64      18.6  393.24   8.05  
..       ...     ...    ...  
364     20.2  354.55   5.29  
370     20.2  392.05   2.96  
375     20.2  396.90  13.44  
453     20.2  375.87  16.74  
482     20.2  395.28   7.01  

[64 rows x 13 columns]

In [ ]:
boston_pd.iloc[0,0]

In [ ]:
boston_pd.loc[sel, ['RM', 'CRIM']]

In [ ]:
boston_sort = boston_pd.sort_values(by='CRIM')

In [ ]:
boston_sort

In [ ]:
boston_pd.shape

In [ ]:
boston_pd.sum()

In [ ]:
boston_pd.mean()

In [ ]:
data = {'Country': ['Belgium', 'India', 'Brazil'], \
'Capital': ['Brussels', 'New Delhi', 'Brasília'], \
'Population': [11190846, 1303171035, 207847528]}
df = pd.DataFrame(data,columns=['Country', 'Capital', 'Population'])

In [ ]:
df

In [ ]:
f = lambda x: x*2

In [ ]:
df.apply(f)

In [ ]:
2*"aa"